### PR TITLE
Use ReactiveElmish.Avalonia

### PR DESCRIPTION
**Pull request by TeaDrivenDev**
@JordanMarr I continued my work over the past few days using the old version of the library, and finally got it to a state where a) it does the absolute minimum for what can be considered "working", and b) I could upgrade to .NET 8 and F# 8 and also move to the new version of Elmish.Avalonia. I'd changed enough that merging your branch would have been a bit messy, so I copied the relevant parts over manually.

I'm running into two issues with this:
- There doesn't currently seem to be a way to add a row to the DataGrid in the design instance. This is obviously minor, and I guess I could just add a method to it that will simply never be called in the running application because there's nothing that could call it.
- It looks like there may need to be a distinction between ViewModels that have a proper view, and ones that are used in a different way, such as `FileViewModel` in this case. Setting one of the settable properties in this implementation causes an error saying that the Elmish loop has not been started, but to do that, I need a control as the view, and there just isn't one. I can pass a new instance of `Control`, which works, but seems arbitrary, and requires opening the `Avalonia.Controls` namespace in ViewModel code, which also doesn't seem right.

### CODE REVIEW

**Comment by JordanMarr** [comment]
_Re: adding a `FileViewModel` in design mode:_

I am working on a more permanent idea for this, but for the immediate term, you have a couple options:

1) In your `init` fn, conditionally add a file if it `IsDesignMode`:
```F#
      Files = 
          let files = ObservableCollection()
          if Avalonia.Controls.Design.IsDesignMode then 
              files.Add(new FileViewModel @"c:\hiberfil.sys")
          files
```

2) Pass in an optional `initialModel` to your `MainWindowViewModel` ctor:

```F#
type MainWindowViewModel(?initialModel) =
    inherit ReactiveElmishViewModel<Model, Message>(defaultArg initialModel (init() |> fst))
```

and then pass in what you want from the `DesignVM`:
```F#
    static member DesignVM =
        let model = init () |> fst
        model.Files.Add(new FileViewModel @"c:\hiberfil.sys")
        new MainWindowViewModel(model)
```

**Comment by JordanMarr** [comment]
Re: "Data" models -- or maybe SubViewModels? 🤔
I agree that there needs to be a built-in way for these sub-vms.

Your temp workaround of passing in a new Control is a good one for now:

```F#

type FileViewModel(path: string) as this =
    inherit ReactiveElmishViewModel<Model, Message>(init path ())

    do  Program.mkAvaloniaSimple (init path) update
        |> Program.withErrorHandler (fun (_, ex) -> printfn "Error: %s" ex.Message)
        |> Program.withConsoleTrace
        |> Program.runView this (new Avalonia.Controls.Control())

    member this.FullName = this.Bind _.FullName
    member this.FileName = this.Bind _.FileName
    member this.Time = this.Bind _.Time
    member this.FileSize = this.Bind _.FileSize

    member this.MoveProgress
        with get () = this.Bind _.MoveProgress
        and set value = this.Dispatch (UpdateProgress value)

    member this.MoveStatus
        with get () = this.Bind _.MoveStatus
        and set value = this.Dispatch (UpdateStatus value)

    override this.StartElmishLoop(view: Avalonia.Controls.Control) = ()

    static member DesignVM = new FileViewModel(@"c:\hiberfil.sys", MoveProgress = 12, MoveStatus = Failed)
```

**Comment by TeaDrivenDev** [comment]
I looked into your suggestion to pass the store from the MainViewModel into the data row ViewModels, but unless I arrange the types very differently that won't work, because `FileOperationViewModel` can't reference the `Model` type from the `Main` module. I resorted to an adapter message and function and another subject for now, but I feel like there's probably a better day to handle this.

**Comment by JordanMarr** [comment]
I see what you mean. Here is another approach: #5.

**Comment by JordanMarr** [comment]
You can use the `AddDisposable` method to dispose when the view model is disposed:
```F#
        // TODO Dispose
        connect
            .Transform(fun file -> new FileViewModel(file))
            .Sort(Comparer.Create(fun (x: FileViewModel) y -> DateTime.Compare(x.Time, y.Time)))
            .Bind(&fileQueue)
            .Subscribe()
            |> this.AddDisposable

```

**Comment by TeaDrivenDev** [comment]
Thanks; that won't work in the `do` block, though, as I don't have access to `this` yet.

**Comment by TeaDrivenDev** [comment]
Forget it; I didn't have the `as this` yet....

**Comment by TeaDrivenDev** [comment]
If `.AddDisposable()` returned the input value again (as the concrete type), one could also do `let copyEngine = CopyFileEngine.create progress |> this.AddDisposable` in cases where a reference to the object is needed later. (But obviously it would need an `|> ignore` then in all other cases,)

**Pull request merged**
